### ISSUE TITLE
[BUG] TypeError: function() argument 'code' must be code, not str

### ISSUE THREAD

**Issue by danielwalo** [mishmashclone/BC-SECURITY-Empire#5]
## Empire Version
Package: powershell-empire (4.2.0-0kali2) 

## OS Information
- VirtualBox: 6.1.30 r148432 (Qt5.6.2)
- OS: Linux kali 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux
- Python: 3.9.9

## Describe the bug
Empire fails to start server or client on an updated Kali VirtualBox VM installation, and instead throws a Python error.

## To Reproduce
1. Install fresh Kali from kali-linux-2021.4a-virtualbox-amd64.ova.torrent
2. Run Empire server successfully
    - sudo powershell-empire server
3. Update Kali:
    - sudo apt update
    - sudo apt upgrade -y
4. Run Empire help command successfully:
    - sudo powershell-empire -h
5. Try to run Empire server again
    - sudo powershell-empire server

## Expected behavior
Server launches.

## Screenshots
```
Traceback (most recent call last):
  File "/usr/share/powershell-empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/usr/share/powershell-empire/empire/server/server.py", line 24, in <module>
    import socketio
  File "/usr/lib/python3/dist-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/lib/python3/dist-packages/socketio/client.py", line 7, in <module>
    import engineio
  File "/usr/lib/python3/dist-packages/engineio/__init__.py", line 8, in <module>
    from .asyncio_client import AsyncClient
  File "/usr/lib/python3/dist-packages/engineio/asyncio_client.py", line 7, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

## Additional context
Tried apt purge followed by apt install, but got the same error.

**Comment by danielwalo** [comment]
Wrong repo.
